#!/bin/bash

DIR_NAME=$1
[ -d $DIR_NAME ] || mkdir $DIR_NAME

cd $DIR_NAME
mkdir pdf
mkdir assets
# More often than not, I name the main file the same as the directory
touch $DIR_NAME.latex
echo "$DIR_NAME".latex >> cfg.cfg
